# 새로운 "Explanation" API로 마이그레이션


In [1]:
# An example dataset and model
import xgboost

import shap

X, y = shap.datasets.adult(n_points=100)
model = xgboost.XGBClassifier().fit(X, y)
explainer = shap.TreeExplainer(model, X)

API의 주요 변경 사항은 다음과 같습니다.


In [2]:
shap_values = explainer.shap_values(X)  # Old style
explanation = explainer(X)  # New style

## SHAP 값 계산 방식의 변화

### 기존 방식 (Legacy Style)

`v0.36.0` 이전 버전에서는 SHAP 설명(Explanation)이 단순한 NumPy 배열로 반환되었으며, 주로 설명자(Explainer)의 `.shap_values()` 메서드를 통해 계산되었습니다.


In [3]:
shap_values = explainer.shap_values(X)
shap_values[:2]  # a numpy array

array([[-0.54854601,  0.01639348, -0.46476041,  0.85896822, -1.36168788,
        -0.64692199,  0.0254638 , -0.58422904, -0.02344483,  0.        ,
         0.1224989 ,  0.01079906],
       [-0.83802091,  0.01562196,  0.78349799, -1.10456323, -0.68524691,
        -0.84828204,  0.03734176, -0.86151311, -0.02564897,  0.        ,
        -0.56183428,  0.00415988]])

마찬가지로 `shap.summary_plot`과 같은 레거시 플로팅 함수는 `shap_values`를 numpy 배열로 예상했습니다.

# 새로운 "Explanation" API로 마이그레이션


In [4]:
explanation = explainer(X)
explanation[:2]  # a shap.Explanation object

.values =
array([[-0.54854601,  0.01639348, -0.46476041,  0.85896822, -1.36168788,
        -0.64692199,  0.0254638 , -0.58422904, -0.02344483,  0.        ,
         0.1224989 ,  0.01079906],
       [-0.83802091,  0.01562196,  0.78349799, -1.10456323, -0.68524691,
        -0.84828204,  0.03734176, -0.86151311, -0.02564897,  0.        ,
        -0.56183428,  0.00415988]])

.base_values =
array([-2.70354599, -2.70354599])

.data =
array([[27.,  4., 10.,  0.,  1.,  1.,  4.,  0.,  0.,  0., 44., 39.],
       [27.,  4., 13.,  4., 10.,  0.,  4.,  0.,  0.,  0., 40., 39.]])

`shap.Explanation` 객체는 단순히 SHAP 값(`.values` 속성)뿐만 아니라, 배경 데이터셋과 특성 이름(feature names) 같은 풍부한 맥락 정보를 포함하고 있습니다.

`shap.plots.bar`나 `shap.plots.beeswarm`과 같은 최신 시각화 함수들은 NumPy 배열 대신 이러한 `Explanation` 객체를 직접 입력으로 받아 더 상세한 시각화를 제공합니다.
