# 새로운 "설명" API로 마이그레이션

이 노트북은 shap 'v0.36.0'에 도입된 shap API의 일부 변경 사항을 보여줍니다.

In [1]:
# An example dataset and model
import xgboost

import shap

X, y = shap.datasets.adult(n_points=100)
model = xgboost.XGBClassifier().fit(X, y)
explainer = shap.TreeExplainer(model, X)

API의 주요 변경 사항을 요약하면 다음과 같습니다.

In [2]:
shap_values = explainer.shap_values(X)  # Old style
explanation = explainer(X)  # New style

## 설명 계산 중

### 예전 스타일

`v0.36.0` 이전 버전의 shap에서는 설명이 간단한 numpy 배열로 표시되고 설명자의 `.shap_values()` 메서드를 사용하여 계산됩니다.

In [3]:
shap_values = explainer.shap_values(X)
shap_values[:2]  # a numpy array

array([[-0.54854601,  0.01639348, -0.46476041,  0.85896822, -1.36168788,
        -0.64692199,  0.0254638 , -0.58422904, -0.02344483,  0.        ,
         0.1224989 ,  0.01079906],
       [-0.83802091,  0.01562196,  0.78349799, -1.10456323, -0.68524691,
        -0.84828204,  0.03734176, -0.86151311, -0.02564897,  0.        ,
        -0.56183428,  0.00415988]])

마찬가지로 `shap.summary_plot`과 같은 레거시 플로팅 함수는 `shap_values`를 numpy 배열로 예상했습니다.

### 새로운 스타일

shap `v0.36.0`부터 ​​설명은 이제 `Explanation` 개체로 표시되며 설명자를 함수로 직접 호출하여 생성됩니다.

In [4]:
explanation = explainer(X)
explanation[:2]  # a shap.Explanation object

.values =
array([[-0.54854601,  0.01639348, -0.46476041,  0.85896822, -1.36168788,
        -0.64692199,  0.0254638 , -0.58422904, -0.02344483,  0.        ,
         0.1224989 ,  0.01079906],
       [-0.83802091,  0.01562196,  0.78349799, -1.10456323, -0.68524691,
        -0.84828204,  0.03734176, -0.86151311, -0.02564897,  0.        ,
        -0.56183428,  0.00415988]])

.base_values =
array([-2.70354599, -2.70354599])

.data =
array([[27.,  4., 10.,  0.,  1.,  1.,  4.,  0.,  0.,  0., 44., 39.],
       [27.,  4., 13.,  4., 10.,  0.,  4.,  0.,  0.,  0., 40., 39.]])

`shap.Explanation` 개체는 shap 값(`.values` 속성으로 액세스 가능)을 포함하고 배경 데이터 세트 및 기능 이름과 같은 상황별 정보를 지원하는 훨씬 더 풍부한 표현입니다.

`shap.plot.bar` 및 `shap.plots.beeswarm`과 같은 새로운 스타일의 플로팅 함수는 numpy 배열 대신 이러한 `설명` 반대 의견을 받아들입니다.